;
; J650 Example  --  MADS-compatible Atari 8-bit executable
; Generated by JPEG-6502
;
; Mode: E  (192 lines)
;

        .org $2000

; ==================================================================
; Entry
; ==================================================================
START   sei
        lda #0
        sta $D400           ; DMACTL off

        ; palette (COLOR0..COLOR4)
        lda #$00
        sta $02C4
        lda #$02
        sta $02C5
        lda #$08
        sta $02C6
        lda #$0E
        sta $02C7
        lda #$00
        sta $02C8

        ; display list pointer
        lda #<DLIST
        sta $0230
        lda #>DLIST
        sta $0231

        ; decompress J650 -> screen RAM
        jsr DECOMPRESS

        ; enable ANTIC
        lda #$22
        sta $022F
        cli

FOREVER jmp FOREVER

; ==================================================================
; Display list
; ==================================================================
DLIST
        .byte $70,$70,$70
        .byte $4E, <SCREEN+0, >SCREEN+0
        .byte $4E, <SCREEN+320, >SCREEN+320
        .byte $4E, <SCREEN+640, >SCREEN+640
        .byte $4E, <SCREEN+960, >SCREEN+960
        .byte $4E, <SCREEN+1280, >SCREEN+1280
        .byte $4E, <SCREEN+1600, >SCREEN+1600
        .byte $4E, <SCREEN+1920, >SCREEN+1920
        .byte $4E, <SCREEN+2240, >SCREEN+2240
        .byte $4E, <SCREEN+2560, >SCREEN+2560
        .byte $4E, <SCREEN+2880, >SCREEN+2880
        .byte $4E, <SCREEN+3200, >SCREEN+3200
        .byte $4E, <SCREEN+3520, >SCREEN+3520
        .byte $4E, <SCREEN+3840, >SCREEN+3840
        .byte $4E, <SCREEN+4160, >SCREEN+4160
        .byte $4E, <SCREEN+4480, >SCREEN+4480
        .byte $4E, <SCREEN+4800, >SCREEN+4800
        .byte $4E, <SCREEN+5120, >SCREEN+5120
        .byte $4E, <SCREEN+5440, >SCREEN+5440
        .byte $4E, <SCREEN+5760, >SCREEN+5760
        .byte $4E, <SCREEN+6080, >SCREEN+6080
        .byte $4E, <SCREEN+6400, >SCREEN+6400
        .byte $4E, <SCREEN+6720, >SCREEN+6720
        .byte $4E, <SCREEN+7040, >SCREEN+7040
        .byte $4E, <SCREEN+7360, >SCREEN+7360
        .byte $41, <DLIST, >DLIST

; ==================================================================
; 6502 J650 Decompressor
; ==================================================================
;
; Zero-page usage:
;   PTR  = $80,$81   J650 data pointer
;   BLEN = $84       block payload length
;   BCOL = $85       block column (pixels, 0..WID)
;   BROW = $86       block row    (pixels, 0..HGT)
;   WID  = $87       image width
;   HGT  = $88       image height
;   TMP  = $8A       general temp
;   VAL  = $8B       pixel value
;   SCRL = $8C,$8D   screen byte pointer (computed by STORE_ABS)
;

PTR     = $80
BLEN    = $84
BCOL    = $85
BROW    = $86
WID     = $87
HGT     = $88
TMP     = $8A
VAL     = $8B
SCRL    = $8C

DECOMPRESS
        lda #<J650
        sta PTR
        lda #>J650
        sta PTR+1

        ldy #4
        lda (PTR),Y
        sta WID
        ldy #6
        lda (PTR),Y
        sta HGT

        ; advance PTR past 12-byte header
        clc
        lda PTR
        adc #12
        sta PTR
        bcc :+
        inc PTR+1
:

        lda #0
        sta BROW
        sta BCOL

; --- main block loop ---
BLOCK_LOOP
        ldy #0
        lda (PTR),Y
        cmp #$FF
        beq EMPTY_BLOCK

        cmp #$01
        bne SKIP_BLOCK

        iny
        lda (PTR),Y
        sta BLEN

        clc
        lda PTR
        adc #2
        sta PTR
        bcc :+
        inc PTR+1
:

        ldy #0
        lda (PTR),Y
        cmp #$02
        beq DECODE_SPARSE
        cmp #$03
        beq DECODE_RLE

        ; --- PACKED (16 bytes) ---
        ldx #0              ; pixel index 0..63
        ldy #0
PACKED_LOOP
        lda (PTR),Y         ; 1 byte = 4 pixels packed 2bpp
        sta TMP

        ; pixel 0 (bits 7-6)
        lda TMP
        lsr
        lsr
        lsr
        lsr
        lsr
        lsr
        and #$03
        jsr STORE_ABS
        inx

        ; pixel 1 (bits 5-4)
        lda TMP
        lsr
        lsr
        lsr
        lsr
        and #$03
        jsr STORE_ABS
        inx

        ; pixel 2 (bits 3-2)
        lda TMP
        lsr
        lsr
        and #$03
        jsr STORE_ABS
        inx

        ; pixel 3 (bits 1-0)
        lda TMP
        and #$03
        jsr STORE_ABS
        inx

        iny
        cpy #16
        bne PACKED_LOOP
        jmp BLOCK_DONE

        ; --- SPARSE (0x02: index,value pairs) ---
DECODE_SPARSE
        ldy #1              ; skip 0x02 marker
SPARSE_LOOP
        lda (PTR),Y
        cmp #$FF
        beq BLOCK_DONE

        tax                  ; X = linear index (0..63)
        iny
        lda (PTR),Y
        and #$03
        iny
        jsr STORE_ABS
        jmp SPARSE_LOOP

        ; --- RLE (0x03: count,value runs) ---
DECODE_RLE
        ldy #1              ; skip 0x03 marker
        ldx #0              ; pixels emitted
RLE_LOOP
        lda (PTR),Y
        cmp #$FF
        beq RLE_ZFILL

        sta TMP              ; count
        iny
        lda (PTR),Y          ; value (0..3)
        and #$03
        iny
RLE_RUN
        jsr STORE_ABS
        inx
        dec TMP
        bne RLE_RUN
        cpx #64
        bcc RLE_LOOP

RLE_ZFILL
        cpx #64
        bcs BLOCK_DONE
        lda #0
        jsr STORE_ABS
        inx
        jmp RLE_ZFILL

        ; --- EMPTY block (0xFF) ---
EMPTY_BLOCK
        inc PTR
        bne :+
        inc PTR+1
:
        lda #0
        ldx #0
EMPTY_LOOP
        jsr STORE_ABS
        inx
        cpx #64
        bne EMPTY_LOOP
        jmp NEXT_BLOCK

        ; --- SKIP unknown block ---
SKIP_BLOCK
        iny
        lda (PTR),Y
        clc
        adc #2
        adc PTR
        sta PTR
        bcc :+
        inc PTR+1
:
        jmp NEXT_BLOCK

BLOCK_DONE
        clc
        lda PTR
        adc BLEN
        sta PTR
        bcc :+
        inc PTR+1
:

NEXT_BLOCK
        lda BCOL
        clc
        adc #8
        sta BCOL
        cmp WID
        bcc BLOCK_LOOP

        lda #0
        sta BCOL
        lda BROW
        clc
        adc #8
        sta BROW
        cmp HGT
        bcc BLOCK_LOOP

        rts

; ==================================================================
; STORE_ABS  -- write pixel A (0..3) at linear index X (0..63)
;               within the current 8x8 block, to SCREEN RAM.
;
; Screen byte = SCREEN + screen_row*40 + screen_col/4
; bit_pair    = (screen_col % 4) * 2
; ==================================================================
STORE_ABS
        sta VAL               ; save pixel value

        ; row_within_block = X / 8
        txa
        lsr
        lsr
        lsr
        clc
        adc BROW              ; screen_row = BROW + row_within
        jsr MUL40             ; A = screen_row * 40
        sta SCRL

        ; col_within_block = X % 8
        txa
        and #$07
        clc
        adc BCOL              ; screen_col = BCOL + col_within

        ; byte_offset = screen_col / 4
        pha                   ; save screen_col
        lsr
        lsr                   ; /4
        clc
        adc SCRL              ; + row*40
        clc
        adc #<SCREEN
        sta SCRL
        lda #>SCREEN
        adc #0
        sta SCRL+1

        ; bit_offset = (screen_col % 4) * 2
        pla                   ; restore screen_col
        and #$03
        asl
        tax

        lda VAL
        and #$03
        cpx #0
        beq STORE_DO

        ; shift pixel value into position
        cpx #2
        beq STORE_SH2
        cpx #4
        beq STORE_SH4
        ; shift=6
        asl
        asl
STORE_SH4
        asl
        asl
STORE_SH2
        asl
        asl

STORE_DO
        ldy #0
        ora (SCRL),Y
        sta (SCRL),Y
        rts

; ==================================================================
; MUL40  -- A = A * 40   (A is 0..191; clobbers TMP)
; ==================================================================
MUL40
        sta TMP
        asl
        asl
        asl
        asl
        asl                   ; *32
        sta $8E
        lda TMP
        asl
        asl
        asl                   ; *8
        clc
        adc $8E
        rts

; ==================================================================
; Data
; ==================================================================
SCREEN  .ds 7680

J650    .ins 'samples\test_deco.j650'

        .end
