"""Generate a MADS-compatible 6502 J650 decompressor and example .asm file.

The generated example.asm bundles:
  - ANTIC display list + palette setup
  - A real 6502 decompressor (handles packed, sparse 0x02, RLE 0x03)
  - The .j650 binary via .ins
  - An infinite-loop display driver
"""

from __future__ import annotations
from pathlib import Path


def generate_example_asm(
    j650_bin_path: str,
    output_asm_path: str,
    antic_mode: str = "E",
    palette: tuple[int, ...] = (0x00, 0x02, 0x08, 0x0E),
) -> str:
    """Generate the complete example.asm and write it to disk."""

    antic_mode = antic_mode.upper()
    if antic_mode == "F":
        line_mode_byte = "$4F"
        mode_byte = "$0F"
        rows = 192
    elif antic_mode == "D":
        line_mode_byte = "$4D"
        mode_byte = "$0D"
        rows = 96
    else:
        line_mode_byte = "$4E"
        mode_byte = "$0E"
        rows = 192

    pal = list(palette)[:5]
    while len(pal) < 5:
        pal.append(0)

    bytes_per_line = 40
    lines_per_4k = 4096 // bytes_per_line  # 102

    # Build 4KB-aware display list
    dl_lines = []
    remaining = rows
    seg_offset = 0
    while remaining > 0:
        seg_lines = min(remaining, lines_per_4k)
        # LMS line
        dl_lines.append(
            f"        .byte {line_mode_byte}, <SCREEN+{seg_offset}, >SCREEN+{seg_offset}"
        )
        # Remaining mode lines in this segment
        for _ in range(seg_lines - 1):
            dl_lines.append(f"        .byte {mode_byte}")
        seg_offset += 4096
        remaining -= seg_lines

    source = f"""\
;
; J650 Example  --  MADS-compatible Atari 8-bit executable
; Generated by JPEG-6502
;
; Mode: {antic_mode}  ({rows} lines)
;

        .org $2000

; ==================================================================
; Entry
; ==================================================================
START   sei
        lda #0
        sta $D400           ; DMACTL off

        ; palette (COLOR0..COLOR4)
        lda #${pal[0]:02X}
        sta $02C4
        lda #${pal[1]:02X}
        sta $02C5
        lda #${pal[2]:02X}
        sta $02C6
        lda #${pal[3]:02X}
        sta $02C7
        lda #${pal[4]:02X}
        sta $02C8

        ; display list pointer
        lda #<DLIST
        sta $0230
        lda #>DLIST
        sta $0231

        ; decompress J650 -> screen RAM
        jsr DECOMPRESS

        ; enable ANTIC
        lda #$22
        sta $022F
        cli

FOREVER jmp FOREVER

; ==================================================================
; Display list
; ==================================================================
DLIST
        .byte $70,$70,$70
{chr(10).join(dl_lines)}
        .byte $41, <DLIST, >DLIST

; ==================================================================
; 6502 J650 Decompressor
; ==================================================================
;
; Zero-page usage:
;   PTR  = $80,$81   J650 data pointer
;   BLEN = $84       block payload length
;   BCOL = $85       block column (pixels, 0..WID)
;   BROW = $86       block row    (pixels, 0..HGT)
;   WID  = $87       image width
;   HGT  = $88       image height
;   TMP  = $8A       general temp
;   VAL  = $8B       pixel value
;   SCRL = $8C,$8D   screen byte pointer (computed by STORE_ABS)
;   SEGL = $8E,$8F   screen segment base (SCREEN + seg*4096)
;

PTR     = $80
BLEN    = $84
BCOL    = $85
BROW    = $86
WID     = $87
HGT     = $88
TMP     = $8A
VAL     = $8B
SCRL    = $8C
SEGL    = $8E

DECOMPRESS
        lda #<J650
        sta PTR
        lda #>J650
        sta PTR+1

        ldy #4
        lda (PTR),Y
        sta WID
        ldy #6
        lda (PTR),Y
        sta HGT

        ; advance PTR past 12-byte header
        clc
        lda PTR
        adc #12
        sta PTR
        bcc :+
        inc PTR+1
:

        lda #0
        sta BROW
        sta BCOL

        lda #<SCREEN
        sta SEGL
        lda #>SCREEN
        sta SEGL+1

; --- main block loop ---
BLOCK_LOOP
        ldy #0
        lda (PTR),Y
        cmp #$FF
        beq EMPTY_BLOCK

        cmp #$01
        bne SKIP_BLOCK

        iny
        lda (PTR),Y
        sta BLEN

        clc
        lda PTR
        adc #2
        sta PTR
        bcc :+
        inc PTR+1
:

        ldy #0
        lda (PTR),Y
        cmp #$02
        beq DECODE_SPARSE
        cmp #$03
        beq DECODE_RLE

        ; --- PACKED (16 bytes) ---
        ldx #0              ; pixel index 0..63
        ldy #0
PACKED_LOOP
        lda (PTR),Y         ; 1 byte = 4 pixels packed 2bpp
        sta TMP

        ; pixel 0 (bits 7-6)
        lda TMP
        lsr
        lsr
        lsr
        lsr
        lsr
        lsr
        and #$03
        jsr STORE_ABS
        inx

        ; pixel 1 (bits 5-4)
        lda TMP
        lsr
        lsr
        lsr
        lsr
        and #$03
        jsr STORE_ABS
        inx

        ; pixel 2 (bits 3-2)
        lda TMP
        lsr
        lsr
        and #$03
        jsr STORE_ABS
        inx

        ; pixel 3 (bits 1-0)
        lda TMP
        and #$03
        jsr STORE_ABS
        inx

        iny
        cpy #16
        bne PACKED_LOOP
        jmp BLOCK_DONE

        ; --- SPARSE (0x02: index,value pairs) ---
DECODE_SPARSE
        ldy #1              ; skip 0x02 marker
SPARSE_LOOP
        lda (PTR),Y
        cmp #$FF
        beq BLOCK_DONE

        tax                  ; X = linear index (0..63)
        iny
        lda (PTR),Y
        and #$03
        iny
        jsr STORE_ABS
        jmp SPARSE_LOOP

        ; --- RLE (0x03: count,value runs) ---
DECODE_RLE
        ldy #1              ; skip 0x03 marker
        ldx #0              ; pixels emitted
RLE_LOOP
        lda (PTR),Y
        cmp #$FF
        beq RLE_ZFILL

        sta TMP              ; count
        iny
        lda (PTR),Y          ; value (0..3)
        and #$03
        iny
RLE_RUN
        jsr STORE_ABS
        inx
        dec TMP
        bne RLE_RUN
        cpx #64
        bcc RLE_LOOP

RLE_ZFILL
        cpx #64
        bcs BLOCK_DONE
        lda #0
        jsr STORE_ABS
        inx
        jmp RLE_ZFILL

        ; --- EMPTY block (0xFF) ---
EMPTY_BLOCK
        inc PTR
        bne :+
        inc PTR+1
:
        lda #0
        ldx #0
EMPTY_LOOP
        jsr STORE_ABS
        inx
        cpx #64
        bne EMPTY_LOOP
        jmp NEXT_BLOCK

        ; --- SKIP unknown block ---
SKIP_BLOCK
        iny
        lda (PTR),Y
        clc
        adc #2
        adc PTR
        sta PTR
        bcc :+
        inc PTR+1
:
        jmp NEXT_BLOCK

BLOCK_DONE
        clc
        lda PTR
        adc BLEN
        sta PTR
        bcc :+
        inc PTR+1
:

NEXT_BLOCK
        lda BCOL
        clc
        adc #8
        sta BCOL
        cmp WID
        bcc BLOCK_LOOP

        lda #0
        sta BCOL
        lda BROW
        clc
        adc #8
        sta BROW

        ; 4KB boundary: at row 102 ($66), advance to next segment
        cmp #$66
        bne :+
        lda SEGL+1
        clc
        adc #$10
        sta SEGL+1
:
        cmp HGT
        bcc BLOCK_LOOP

        rts

; ==================================================================
; STORE_ABS  -- write pixel A (0..3) at linear index X (0..63)
;               within the current 8x8 block, to SCREEN RAM.
;
; Screen byte = SCREEN + screen_row*40 + screen_col/4
; bit_pair    = (screen_col % 4) * 2
; ==================================================================
STORE_ABS
        sta VAL               ; save pixel value

        ; row_within_block = X / 8
        txa
        lsr
        lsr
        lsr
        clc
        adc BROW              ; screen_row = BROW + row_within
        jsr MUL40             ; A = screen_row * 40
        sta SCRL

        ; col_within_block = X % 8
        txa
        and #$07
        clc
        adc BCOL              ; screen_col = BCOL + col_within

        ; byte_offset = screen_col / 4
        pha                   ; save screen_col
        lsr
        lsr                   ; /4
        clc
        adc SCRL              ; + row*40
        clc
        adc SEGL
        sta SCRL
        lda SEGL+1
        adc #0
        sta SCRL+1

        ; bit_offset = (screen_col % 4) * 2
        pla                   ; restore screen_col
        and #$03
        asl
        tax

        lda VAL
        and #$03
        cpx #0
        beq STORE_DO

        ; shift pixel value into position
        cpx #2
        beq STORE_SH2
        cpx #4
        beq STORE_SH4
        ; shift=6
        asl
        asl
STORE_SH4
        asl
        asl
STORE_SH2
        asl
        asl

STORE_DO
        ldy #0
        ora (SCRL),Y
        sta (SCRL),Y
        rts

; ==================================================================
; MUL40  -- A = A * 40   (A is 0..191; clobbers TMP)
; ==================================================================
MUL40
        sta TMP
        asl
        asl
        asl
        asl
        asl                   ; *32
        sta $8E
        lda TMP
        asl
        asl
        asl                   ; *8
        clc
        adc $8E
        rts

; ==================================================================
; Data
; ==================================================================
SCREEN  .ds 4080            ; lines 0..101: 102*40 = 4080 bytes
        .ds 16              ; padding to align 4KB boundary
        .ds 3600            ; lines 102..191: 90*40 = 3600 bytes

J650    .ins '{j650_bin_path}'

        .end
"""
    Path(output_asm_path).write_text(source, encoding="utf-8")
    return source
